version: '3.7'

services:
  traefik:
    image: traefik:v1.7.6 # The official Traefik docker image
    restart: always
    command: --api --docker --logLevel=DEBUG # Enables the web UI and tells Traefik to listen to docker
    ports:
      - 80:80     # The HTTP port
      - 443:443
    #  - 8080:8080 # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./traefik.toml:/traefik.toml
    labels:
      - traefik.docker.network=frontend
      - traefik.enable=true
      - traefik.frontend.rule=Host:traefik.localhost
      - traefik.frontend.protocol=http
      - traefik.port=8080
      - "traefik.http.routers.proxy=Host('traefik.localhost')"
    networks:
      - frontend
  portainer:
    image: portainer/portainer:latest # The official Traefik docker image
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - portainer:/data
    labels:
      - traefik.docker.network=frontend
      - traefik.enable=true
      - traefik.frontend.rule=Host:portainer.localhost
      - traefik.frontend.protocol=http
      - traefik.port=9000
    networks:
      - frontend

  mysql:
    image: mysql:8
    restart: on-failure
    environment:
      MYSQL_DATABASE: perse
      MYSQL_USER: perse_user
      MYSQL_PASSWORD: perse_password
      MYSQL_ROOT_PASSWORD: root_password
#      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - perse-mysql:/var/lib/mysql
      - .:/perse:delegated
    ports:
      - "3306:3306"
    networks:
      - backend

  symfony:
    links:
      - mysql:db
    depends_on:
      - mysql
    build:
      context: .
      target: perse-php
    entrypoint: ./bin/symfony serve
    environment:
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_INTL: 1
      PHP_EXTENSION_MCRYPT: 1
      PHP_EXTENSION_UUID: 1
    volumes:
      - ./api:/var/www/html:delegated
    labels:
      - traefik.docker.network=frontend
      - traefik.enable=true
      - traefik.frontend.rule=Host:perse.localhost;PathPrefix:/api
      - traefik.frontend.protocol=http,https
      - traefik.port=8000
    networks:
      - frontend
      - backend
  angular:
    build:
      context: .
      target: perse-angular
    entrypoint: ng serve --host 0.0.0.0 --port 4300 --disableHostCheck
    environment:
      SERVER_ENV: dev
    volumes:
      - type: bind
        source: ./angular
        target: /var/www/html
        consistency: delegated
    labels:
      - traefik.docker.network=frontend
      - traefik.enable=true
      - traefik.frontend.rule=Host:perse.localhost
      - traefik.frontend.protocol=http,https
      - traefik.port=4300
    networks:
      - frontend


volumes:
  perse-mysql:
  portainer:

networks:
  backend:
  frontend:
    external: true
